# Nome da aplicação
spring.application.name=TurisGuide

# Configuração do servidor
server.port=8081

# Configuração do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:2222/tgdb
spring.datasource.username=postgres
spring.datasource.password=banco123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configurações de logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configurações de encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Configurações do DevTools para Hot Reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**,public/**,templates/**

#JWT Token
api.security.token.secret=${JWT_SECRET:my-secret-key}